In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### 0. Simulate dataset

In [48]:
np.random.seed(42)

samples = 1000
features = 2

X = np.random.rand(samples, features)
X = np.c_[np.ones(len(X)), X]
epsilon = np.random.randn(samples)

y = 3 * X[:,1] + 5 * X[:,2] + 3 + epsilon
y = y.reshape(samples,1) # y shape (1000,) -> (1000, 1)

print(epsilon.shape)
X[:3], X.shape, y[:3], y.shape


#-----------------------
# alt to calculate y by dot product
# betas = np.array([3, 3, 5])
# y = np.dot(X, betas) + epsilon


(1000,)


(array([[1.        , 0.37454012, 0.95071431],
        [1.        , 0.73199394, 0.59865848],
        [1.        , 0.15601864, 0.15599452]]),
 (1000, 3),
 array([[7.9992093 ],
        [7.36239389],
        [4.02154963]]),
 (1000, 1))

### 1. Gradient descent - learning rate

#### a)

In [65]:
# create gradient descent function updating theta epochs number of times
np.random.seed(42)

def batch_gradient_descent(X, y, learning_rate, epochs):
    m = len(X)

    theta = np.random.randn(X.shape[1], 1) # generate initial random theta with # rows dimension matching # columns in X (X.shape[1])

    for _ in range(epochs):
        gradient = 2 / m * X.T @ (X @ theta - y)
        theta -= learning_rate * gradient
    return theta.reshape(-1)


In [66]:
# testing functioin to generate theta
theta = batch_gradient_descent(X, y, learning_rate = .1, epochs = 500)
theta

array([3.12072048, 2.95398747, 4.83284202])

In [70]:
# create array of thetas

learning_rate = 0.1
epochs = 500
step = 5

epoch_list = range(1, epochs, step)
thetas = np.array([batch_gradient_descent(X, y, learning_rate = learning_rate, epochs = epochs) for epoch in epoch_list])

print(f'{thetas[:3]}, {thetas.shape}')

[[3.12149913 2.95341851 4.83194248]
 [3.1223724  2.95261896 4.83108972]
 [3.11924438 2.95513083 4.83448469]], (100, 3)
